### PR TITLE
Feature/typescript

### PR DESCRIPTION
**Pull request by deinok**
This ports all the code to *.ts files.
Also, it exposes the library as TypeScript and JavaScript.

### CODE REVIEW

**Comment by deinok** [comment]
@wstoettinger I think this is ready to be merged to features/typescript

**Comment by wstoettinger** [comment]
thanks!

**Comment by wstoettinger** [comment]
looks quite good, thanks! i have a view questions though: what was the reason why you chose to compile with tsc again in favor of webpack? is there something webpack cant compile with the ts-loader? the other thing i was a bit confused about, is the .ts file in the dist directory. i'm used to have only generated content in the dist directory which can be re-generated every time (even after deleting the whole directory) and which is ready for immediate use. 

please clarify. thanks!

**Comment by deinok** [comment]
Well, for me the dist directory is where all the "Release" content is putted.
So, if you want to consume the library with TS, you catch the .ts file, if you want the JavaScript version you catch the .min.js or js.

And about the ts-loader: if we can target TS to ES3 and make the ES2015 modules work on ES3 we should be able to reduce the size of the .min.js (WebPack writes a lot of code).

**Comment by deinok** [comment]
@wstoettinger if you could give me rights to the feature/typescript branch i would be able to work faster :)

**Comment by wstoettinger** [comment]
unfortunately I can't since i don't have admin rights. this has to be done by @mikegreiling

**Pull request merged**
