### PR TITLE
Responsive images

### PR DESCRIPTION
**Pull request by stefhatcher**
Apologies if this went too rogue. A summary of the changes:

- Added responsive functionality (default is false).
- Dynamic aspect ratios for responsive images.
- Loaded responsive images are stored and prevented from loading unnecessarily.
- Responsive images work on iOS and Android.
- Added opacity when parallax element is visible or not.
- Added a custom build of Modernizr which tests a given media query, live against the current state of the window. Modernizr is used when responsive is true.
- Added Grunt to build out versions of the library with/without Modernizr concatenated.
- Added JSHint.
- Updated the README

Grunt's functionality can be achieved with the following commands:
```shell
uglifyjs lib/parallax.js --comments -m -c -o dist/parallax.min.js
cat vendor/modernizr.mq.min.js lib/parallax.js > lib/parallax.mq.js
cat vendor/modernizr.mq.min.js dist/parallax.min.js > dist/parallax.mq.min.js
```
I wouldn't be opposed to removing Grunt & JSHint and suggest to run those commands instead.

Thoughts?

### CODE REVIEW

**Comment by mikegreiling** [comment]
Hey @stefhatcher sorry I've taken so long to respond to this.  Work has kept me away from my open source stuff for a while.

This PR looks good, and I don't mind the inclusion of Grunt and JSHint.  I have a few questions though before I can merge this.

* When the modernizr-included build is run and a page already includes that library, are there any conflicts, or will the duplicate method be silently overridden?

* In your opinion, is the use of <span> elements to designate responsive images the best way to handle this?  I haven't been keeping up with all of the latest changes in responsive image implementations, but when I had considered the feature before I imagined using something akin to the image `srcset` and `sizes` attributes, or perhaps the `<source>` element like the one used alongside the `<picture>` element.  I think this would be more familiar to people who have worked with responsive images before...  any thoughts?

* Isn't the `opacity` attribute redundant when setting `visibility`?  What is your rationale for including it?

Also before merging this PR, I'll need you to update the repo and license urls in `package.json` to point to the pixelcog repo. (and re-run grunt so the changes appear in the compiled headers)

I'd also like to retain the `@copyright` notice and project url (http://pixelcog.github.io/parallax.js/) within the header.

Great work, and thanks for putting in the time!

**Comment by benjaminpick** [comment]
Modernizr: I was testing this and currently the (complete) Modernizr-library is overwritten depending on whatever is loaded first. So probably we should include a check `if (typeof(window.Modernizr) == 'undefined')` around it or put it into a private variable.

**Comment by stefhatcher** [comment]
Hello @mikegreiling !

My apologies for taking so long to reply. I started a new job and it's been a whirlwind :)

Ideally, if a user is using Modernizr in a project and including it in the recommended spot, the user will use `parallax.js`/`parallax.min.js` instead of using the media query included versions `parallax.mq.js`/`parallax.mq.min.js` to eliminate redundant code. I used the Modernizr free version of parallax.js on a project because Modernizr was already included, but for a more standalone version of parallax.js, I added a custom build of Modernizr. To prevent any conflict, I scoped the custom build of Modernizr to `CustomModernizr`, using `CustomModernizr` if available and defaulting to `Modernizr`. If neither are available then ¯\_(ツ)_/¯.

I modeled the responsive image portion after the `<picture>` and `<source>` elements. I chose `<div>` to replace `<picture>` and `<span>` to replace  `<source>` for a few reasons:
- Future-proofing: div and span implementations are probably not going to change cross-browser in the future as much as picture and source elements might.
- No need for polyfills.
- Better cross-browser support.
- Using data attributes as config options and setters follows the parallax.js implementation style.
- Using elements to designate responsive images and sources, to me, is easier to read and maintain than chunks of strings like some of the other responsive image approaches.

In all honesty, I forget *why* I added `visibility` other than it fixed a flickering that was happening to a hero image in a project I was using this version of parallax.js. I just tested it out in Chrome without the `visibility` and the bug seems to have been with that version of Chrome at the time - I cannot reproduce it. :/ So, I updated the PR to not use it!

Updated the `package.json` and banner! Wasn't sure if it was supposed to reflect my version of it or the state of it being merged into `pixelcog/parallax.js`!

Thanks for looking everything over!

**Comment by benjaminpick** [comment]
Hi @stefhatcher,

I am currently trying to use your version. What I do not understand from the documentation alone:
- If I am reading the queries right, it is "if window width is 800px, use the 767 image." ?
- How do I write: "otherwise, if no media query is matching this, use the 320 image" or similar? Currently for 320px there is no image shown.
- Is the order of the media queries important, ie a later match overwrites a first match?

**Comment by stefhatcher** [comment]
Hello! Yes! Order is important - much like in media queries in CSS. Starting from the first element, it checks each media query until it finds one that matches the current device-width - Modernizr.mq returns true that the media query matches.

Take this example with very simple media queries:
```html
<html>
  <head>
    <meta content="width=device-width" name="viewport">
    <style>
      html, body {
        height: 100%;
        width: 100%;
      }

      body {
        margin: 0;
        padding: 0;
      }

      .parallax-window {
        height: 100vh;
      }
    </style>
  </head>
  <body>
    <div class="parallax-window" data-parallax="scroll" data-responsive="true">
      <span data-image-src="http://placehold.it/767x767/" data-media-query="(min-width: 320px)"></span>
      <span data-image-src="http://placehold.it/1024x1024/" data-media-query="(min-width: 768px)"></span>
      <span data-image-src="http://placehold.it/1200x1200/" data-media-query="(min-width: 1024px)"></span>
      <span data-image-src="http://placehold.it/1400x1400/" data-media-query="(min-width: 1200px)"></span>
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="/path/to/dist/parallax.mq.min.js">
  </body>
</html>
```

The '767x767' image will load for widths 0px - 766px because the media query `(min-width: 320px)` matches first until the device-width of 767px and `(min-width: 767px)` becomes true and matches. The '1024x1024' image will be visible until a device-width of 1024px, when `(min-width: 1024px)` matches best and the '1200x1200' image will be used. If the following were to be added as the first span element, before the 320px one, it would show up from 0px - 319px:

```html
<span data-image-src="http://placehold.it/320x320/" data-media-query="(min-width: 0px)"></span>
```

**Comment by benjaminpick** [comment]
Taking the first element actually is consistent with the <picture>
syntax, I was confused because CSS takes the last matching element.

I don't understand, however, why the 767 image should be matched when
window viewport is 300px width ... it would make some sense because it
is better than to show no image at all, but when I tested it actually
showed nothing in this case. At the same time the library cannot be sure
that the first image is the smallest (as inversing the order would give
the same result here), that's why I'd suggest using the data-image-src
on the div element as default image. This would make backwards
compability more easy and leaves more margin for user errors.

Anyway, many thanks for your work @stefhatcher!

**Comment by benjaminpick** [comment]
I have sent a documentation pull request to @stefhatcher.

Actually, currently the code takes the last matching media query otherwise your example would always match the first image (1200px > 320px so Image Found!). @mikegreiling Which logic do you find more appropriate?

**Comment by stefhatcher** [comment]
The reason the 767px image was showing when the viewport was less than 320px is because it was the first loaded and defaulted to that instead of displaying nothing. Now, I updated it to default to `data-image-src` on the parallax element if no media query matches. If `data-image-src` is not set, it defaults to a 1x1 transparent gif.

**Comment by benjaminpick** [comment]
@stefhatcher In IE8, I get the error message "this.$slider.0 is null or not an object". This error is probably from this pull request as the original version does not throw it.

**Comment by dennisfrank** [comment]
@mikegreiling Any chance that this PR will be merged into the master branch?

**Comment by wstoettinger** [comment]
i think this can be achieved by #88 which got merged.

**Pull request closed without merging**
