### PR TITLE
Add loaded callback functionality

### PR DESCRIPTION
**Pull request by quochuy**
This allows me to set a background color on the parallax container, then when the image is loaded, set the background color to transparent as required.

### CODE REVIEW

**Comment by quochuy** [comment]
This allows me to set a background color on the parallax container, then when the image is loaded, set the background color to transparent as required.

**Comment by quochuy** [comment]
Found a bug with this implementation, because options is shared, options.loaded is only called by the last parallax item on the page.

**Comment by wstoettinger** [comment]
without having it tested yet, i think my last commit should meet your requirements and fire each time a parallax slider is loaded. Can you confirm this?

**Comment by vesper8** [comment]
please add this... it's needed

**Comment by wstoettinger** [comment]
this is part of v2

**Pull request closed without merging**
