### PR TITLE
enabling complex html as background slider

### PR DESCRIPTION
**Pull request by wstoettinger**
This appends a whole DOM element to the parallax mirror (utilizing the
same ".parallax-slider" class).

so far it only works properly when setting the naturalWidth and
naturalHeight options in the JS initialization. Somebody got a tip on
how to improve that?

I'm planning to implement a parallax carousel which should be possible
with that change.

also performance improvement suggestions from #71

### CODE REVIEW

**Comment by wstoettinger** [comment]
@ninjaonsafari, @ninjaonsafari maybe this is interesting for you

**Comment by Stefanowitsch84** [comment]
could you provide a html markup example? I can't get this to work. I can see the HTML Content in the parallax element but doesn't move when scrolling.

**Comment by wstoettinger** [comment]
I'm sorry for my late response, I haven't been using it until now, so I couldn't provide an example.

So here is the simple one:
```html
<div class="parallax-window">
  <div class="parallax-slider">
      <span style="position:absolute; top: 400px; left: 400px;">Some Text</span>
      <img src="/path/to/image.jpg">
    </div>
  </div>
</div>
```
To get it to work you need to instantiate it with the following JavaScript. You have to provide naturalWidht and natualHeight, although they don't necessarily need to be right, the aspect ratio should be correct.

```javascript
$('.parallax-window').parallax({
        naturalWidth: 600,
        naturalHeight: 400
      });
```

I'm using a more complex solution. 'The' ultimate responsive image carousel parallax solution ;) I managed to get it to work with an owl slider. I'm also using lazyload.js and responsive images. Unfortunately the click events don't get through to the parallax slider, otherwise the featherlight gallery would also work ;). It works on mobile though. 
```html
<!-- parallax elements -->
<div class="parallax-window" > 
  <div class="parallax-slider"> 
    <!-- owl elements -->
    <div class="owl-carousel">
      <div class="owl-slide">
        <!-- featherlight elements, only work on mobile -->
        <a href="#carousel-image-0">
          <div id="carousel-image-0" >
            <!-- actual content: responsive, lazyloaded image -->
            <picture>
              <img alt="" title="" class="lazyload" sizes="100vw"
                          src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7"
                          data-src="/static/img/port/aktion/DSC_4593.jpg"
                          data-srcset="/static/img/port/aktion/DSC_4593-660w.jpg 660w, /static/img/port/aktion/DSC_4593-712w.jpg 712w, /static/img/port/aktion/DSC_4593-960w.jpg 960w, /static/img/port/aktion/DSC_4593-1088w.jpg 1088w, /static/img/port/aktion/DSC_4593-1280w.jpg 1280w, /static/img/port/aktion/DSC_4593-1440w.jpg 1440w, /static/img/port/aktion/DSC_4593-1600w.jpg 1600w, /static/img/port/aktion/DSC_4593-1920w.jpg 1920w, /static/img/port/aktion/DSC_4593-2400w.jpg 2400w, /static/img/port/aktion/DSC_4593-2880w.jpg 2880w">
            </picture>
          </div>
        </a>
      </div>
      <div class="owl-slide">
        <a href="#carousel-image-1">
          <div id="carousel-image-1" class="picture-wrapper">
            <!-- second picture goes here -->
          </div>
        </a>
      </div>
    </div>
  </div>
</div>
```

**Comment by awojtczyk** [comment]
wstoettinger, is there any chance to provide some simple demo of owl-carousel and parallax.js together please?

**Comment by wstoettinger** [comment]
i just realized, that i forgot to add the JS code which i used to make it work.

```javascript
    // first, initialize the owl carousel
    $('.owl-carousel').owlCarousel({
        items: 1,
        loop: true,
        autoplay: true,
        autoplayHoverPause: true,
        nav: true,
        navText: ['', ''],
        margin: 15,
        navContainer: '#owl-reviews .owl-nav',
        dotsContainer: '#owl-reviews .owl-dots'
    });

    // then init parallax, you need to provide "natualWidth" and "naturalHeight" in a proper ratio
    // note, that the absolute values of the width and height are not that important, but the ratio is.
    $('.parallax-window').parallax({
        naturalWidth: 2880,
        naturalHeight: 1920
    });

    // trigger a refresh of the owl carousel after the parallax is initialized
    // this is necessary so the size of the owl is properly calculated after it's converted to the parallax
    setTimeout(function () {
        if($owl.data('owlCarousel'))
          $owl.data('owlCarousel').onResize();
    },100);
```

**Comment by awojtczyk** [comment]
Great, If it will work, I'll drop link to full demo later. Thank you!

**Pull request merged**
