### PR TITLE
Support parallax for mobile devices

### PR DESCRIPTION
**Pull request by ktsn**
Hello! I have read the past issue #67 and I see why parallax.js does not support mobile devices. However, looks like the recent mobile devices fire scroll event during the user is scrolling the window, not only when the scroll is finished.

In addition, I seem we can handle the scroll event by using `touchmove` event for old devices.

So I've added mobile device support in this PR. The PR includes:

* Introduce `iosDisabled` and `androidDisabled` options for backward compatibility (default is `true`)
* Add `touchmove` event listener for old devices that does not handle `scroll` event during scrolling.
  * It uses `passive` event listener if possible.

I've tested this change with iOS/Android devices which I have by using this code. https://github.com/ktsn/parallax.js-test

If I'm missing something important to support mobile devices. Please let me know.

Thank you!

### CODE REVIEW

**Comment by cfriedt** [comment]
I just applied this changeset and it had no visible effect for my Android 7.0.0 device (Chrome 62.0.3202.84) nor for my wife's iOS 11.2 device (with whatever Safari version is running).

I made sure that both androidDisabled and iosDisabled were initialized to false in both parallax.js and parallax-min.js. 

However, if I manually select "Request desktop site" in chrome, parallax works, but that was already the case without this patch.

**Comment by cfriedt** [comment]
I tested this on Android 7.0.0 (Chrome 62 something) and iOS 11.2 (Safari) and it worked in both cases when androidDisabled and iosDisabled were initialized to false.

**Comment by BraveLilToaster** [comment]
Just tested it as well. Looks great. I'm going to be pushing this out to some sites right now.

**Comment by oliverschloebe** [comment]
Tested on Android 9 (Chrome 78) and iOS 13 (Safari) and it's working fine. Thanks for this. 👍

**Comment by jtsimoes** [comment]
I love this! You really need to merge it! @wstoettinger

**Pull request merged**
