### PR TITLE
Improved animation technique, fixes an issue which causes to scroll the parallax divs to a different speed

### PR DESCRIPTION
**Pull request by DevNIX**

### CODE REVIEW

**Comment by DevNIX** [comment]
I've removed the old `requestAnimationFrame` and implemented a way faster version. This should end every problem about mirror moving at a different speed of the current scroll!

**Comment by thegallagher** [comment]
In my testing, this technique is very much an improvement. Nice work. I hope this gets pulled soon.

**Comment by DevNIX** [comment]
Thank you so much! I think there could be a better whole approach to achieve more performance, as I feel the fixed layout is an overkill; specially when you are reflowing the content.

**Comment by BeginHere** [comment]
Thank you @DevNIX ! This completely fixed jumpy scrolling in Safari for me.

**Comment by benjamin-richardson** [comment]
Thanks a lot for putting this update together, much better animations. I have also added 'will-change: transform;' to my CSS for maximum performance.

**Comment by ooloth** [comment]
Thanks @DevNIX! This fixed my Safari issues as well.

**Pull request merged**
