### PR TITLE
Parallax will not work unless you add the class selector

### PR DESCRIPTION
**Pull request by the94air**

### CODE REVIEW

**Comment by the94air** [comment]
WOW, That has take a long time. OK thanks :+1:

**Comment by wstoettinger** [comment]
The usage of data attributes and javascript are supposed to be excluding options. Either use the one, or the other.  The explanation you provided applies to the javascript usage (which is explained below), in case the data-attribute usage does not work, please raise a new issue.

**Comment by wstoettinger** [comment]
okay, this seems to be a confirmed bug since 2016. see #183

**Comment by the94air** [comment]
Ok, as you like :smile:.

**Pull request closed without merging**
