### PR TITLE
Added opacity/background support for images

### PR DESCRIPTION
**Pull request by anija**
To use parallax.js with images and text, it's nice to have control of the image transparency.

### CODE REVIEW

**Comment by caseydev** [comment]
you meant we can use as background-image instead of data-image-src on html. So how i have tried to add from parallax class selector but its not working for me.

**Comment by anija** [comment]
@caseydev you have to use the two new options (https://github.com/pixelcog/parallax.js/pull/122/commits/95add44704ee6ac0c44649cbb53f16e4b3ee9408#diff-04c6e90faac2675aa89e2176d2eec7d8R175):


- opacity: (number, default:1) to customize the image transparency.
- background: (string, dafault: null) to customize the background behind the image (works with opacity < 1).

**Comment by wstoettinger** [comment]
this looks like a nice addition, but I think this is also possible via CSS and doesn't need a change in the JS source.

**Comment by caseydev** [comment]
@anija thanks i have got.

**Pull request closed without merging**
