### PR TITLE
Added a package.json file for NPM compatibility.

### PR DESCRIPTION
**Pull request by foglerek**
More and more packages are moving away from bower.

Please consider merging this pull request and publishing this package on npm: https://docs.npmjs.com/getting-started/publishing-npm-packages.

Thanks!

### CODE REVIEW

**Comment by foglerek** [comment]
Related to issue#91

**Comment by joemaller** [comment]
@foglerek thanks for putting this together, I'd like to see parallax.js on npm as well. Besides the line notes above, the version should be bumped too.

**Comment by foglerek** [comment]
Shoot! Sorry about that, did not even notice.

Fixing and pushing.

**Comment by foglerek** [comment]
Done!

**Comment by vutran** [comment]
+1

**Comment by foglerek** [comment]
Hey, I bumped the version to 1.4.3 now (most recent).

**Comment by acezard** [comment]
+1

**Comment by of6** [comment]
👍 
Any chance this could be added soon? I'd love to use npm for this instead of manually adding it :)

**Comment by LFeh** [comment]
+1

**Comment by wstoettinger** [comment]
merged with #173

**Pull request closed without merging**
